name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache build data
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify formatting
        run: gofmt -l ./ | tee /tmp/gofmt.out && test ! -s /tmp/gofmt.out

      - name: Go vet
        run: go vet ./...

      - name: Unit tests with coverage
        run: go test ./... -coverprofile=coverage.out
        env:
          GOCACHE: ${{ github.workspace }}/.cache/go-build

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
